apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ui
spec:
  rules:
  - host:
    http:
      paths:
      - path: /
        backend:
          serviceName: consul-ui
          servicePort: 8500

