version: "3.7"
services:
    nodeserver1:
        build:
            context: ./app
        ports:
            - "5000:5000"
        environment:
            SERVER_NAME: "server1"
            PORT: 5000
            TARGET_HOST: "nginx"
            TARGET_URI: "server2"
        networks:
            - warnetwork
    nodeserver2:
        build:
            context: ./app
        ports:
            - "5001:5001"
        environment:
            SERVER_NAME: "server2"
            PORT: 5001
            TARGET_HOST: "nginx"
            TARGET_URI: "server1"
        networks:
            - war_network
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "81:80"
        networks:
            - warnetwork
networks:
    warnetwork :
        driver: bridge