apiVersion: k3s.cattle.io/v1
kind: HelmChart
metadata:
  name: nfs
  namespace: kube-system
spec:
  chart: stable/nfs-server-provisioner
  targetNamespace: nfs-provisioner
  valuesContent: |-
    storageClass:
      defaultClass: true

